name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ta-lib
  - numpy
  - pandas
  - matplotlib
  - yfinance
  - scikit-learn
  - xgboost
  - pip
  - pip:
    - # Add any pip-only dependencies here
    - datetime
    - flask
    - plotly